# Generated by Django 4.2.16 on 2024-12-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheema_retail_store', '0002_rename_images_product_images_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_urls',
            field=models.JSONField(null=True),
        ),
    ]
