# Generated by Django 4.2.16 on 2024-12-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheema_retail_store', '0003_alter_product_images_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_urls',
            field=models.JSONField(default=list),
        ),
    ]
